// Generated by tools/generate_compatibility.py. Do not edit by hand.
#pragma once
#include <cstddef>
#include <cstdint>
namespace dolly { namespace reviewed {
struct CodeSpan { std::uintptr_t rva; std::size_t size; };
struct NamedRva { const char* name; std::uintptr_t rva; };
namespace Preload {
inline constexpr char CLIENT_SHA256[] = "e2bafed8ebdfd239d506b4f59b24a09719f945c6a63f69766171349b886603d4";
inline constexpr char RESOURCE_SHA256[] = "fba2c4733b0b3913ddf46cd26158f29b2ff87dfb06f9ab1b63da3361f0528800";
inline constexpr std::uintptr_t MANAGER = 0x321aa30;
inline constexpr std::uintptr_t MANAGER_VTABLE = 0x26c1440;
inline constexpr std::uintptr_t RESOURCE_GLOBAL = 0x3ea2370;
inline constexpr std::uintptr_t RESOURCE_VTABLE = 0x6bc58;
inline constexpr std::uintptr_t RESOURCE_QUERY = 0x1c860;
inline constexpr std::uintptr_t INTRO_GLOBAL = 0x3d00d38;
inline constexpr std::uintptr_t INTRO_VTABLE = 0x2b6aa58;
inline constexpr CodeSpan CLIENT_CODE_SPANS[] = {{0x5f4da0, 8}, {0x5fe040, 126}, {0x1d510c0, 266}, {0x5e5fce, 51}, {0x601490, 10}, {0x5da710, 75}, {0x1b18945, 101}, {0x1b35110, 230}, {0x1b5b09e, 465}, {0x1b43920, 66}, {0x1b20bb0, 554}};
inline constexpr std::uintptr_t MANAGER_SIZE = 0x40;
inline constexpr std::uintptr_t COMPLETED = 0x24;
inline constexpr std::uintptr_t RESOURCE = 0x30;
inline constexpr std::uintptr_t JOB = 0x38;
inline constexpr std::uintptr_t LIFECYCLE_BEGIN = 0x3c;
inline constexpr std::uintptr_t LIFECYCLE_END = 0x3e;
inline constexpr std::uintptr_t RESOURCE_QUERY_SLOT = 0xc0;
inline constexpr std::uintptr_t RESOURCE_DONE = 0x44;
inline constexpr std::uintptr_t INTRO_SIZE = 0x84;
inline constexpr std::uintptr_t INTRO_PHASE = 0x80;
}
namespace ReplayCamera {
inline constexpr char CLIENT_SHA256[] = "e2bafed8ebdfd239d506b4f59b24a09719f945c6a63f69766171349b886603d4";
inline constexpr std::uintptr_t MANAGER = 0x36da370;
inline constexpr std::uintptr_t MANAGER_VTABLE = 0x26bab80;
inline constexpr std::uintptr_t GAMEPLAY_CAMERA_VTABLE = 0x26c25c8;
inline constexpr std::uintptr_t RULES_GLOBAL = 0x3ce4160;
inline constexpr std::uintptr_t RULES_VTABLE = 0x26f6cd8;
inline constexpr CodeSpan CODE_SPANS[] = {{0x5d7120, 685}, {0x5b9d50, 181}, {0x1874a30, 261}, {0x1889a70, 5}, {0x188db90, 6}, {0x1b72da0, 1642}, {0x1918bf0, 88}, {0x1b22890, 17}, {0x1b54d69, 112}, {0x1b6c5d0, 91}, {0x1b72a50, 118}};
inline constexpr std::uintptr_t RULES_STATE = 0x74;
inline constexpr std::uintptr_t MANAGER_SIZE = 0x48;
inline constexpr std::uintptr_t CURRENT_CAMERA = 0x28;
inline constexpr std::uintptr_t BLENDING = 0x38;
inline constexpr std::uintptr_t BLEND_WEIGHT = 0x44;
inline constexpr std::uintptr_t HUD_ROOT = 0x3d00158;
inline constexpr std::uintptr_t HUD_ROOT_VTABLE = 0x2b66c80;
inline constexpr std::uintptr_t HUD_TAKEOVER_COUNT = 0x284;
}
namespace FollowCapabilities {
inline constexpr char TIER0_SHA256[] = "6793cc7306ff40283ba038a784fe96f99f6d38f93c825571ee93ab6b9d9d5332";
inline constexpr CodeSpan CLIENT_SPANS[] = {{0x8efc0, 3430}, {0x90710, 166}, {0x236ff0, 115}, {0x243da40, 129}, {0x254920, 10}, {0x60d1d6, 11}};
inline constexpr CodeSpan TIER0_SPANS[] = {{0x20fd40, 633}};
inline constexpr NamedRva REFS[] = {{"pivot_x_offset", 0x36dbde0}, {"pivot_y_offset", 0x36dbdf0}, {"pivot_z_offset", 0x36dbe00}, {"pivot_x_offset_crouching", 0x36dbe10}, {"pivot_y_offset_crouching", 0x36dbe20}, {"pivot_z_offset_crouching", 0x36dbe30}, {"x_offset", 0x36dbe40}, {"y_offset", 0x36dbe50}, {"z_offset", 0x36dbe60}, {"x_worst_case_offset", 0x36dbe70}, {"y_worst_case_offset", 0x36dbe80}, {"z_worst_case_offset", 0x36dbe90}, {"ads_x_offset", 0x36dbea0}, {"ads_y_offset", 0x36dbeb0}, {"ads_z_offset", 0x36dbec0}, {"fov", 0x36dbed0}, {"ads_fov", 0x36dbee0}};
inline constexpr CodeSpan OWN_HEALTH_SPANS[] = {{0x1bc130, 174}, {0x1b5f5a0, 803}, {0x1b41680, 47}};
inline constexpr std::uintptr_t ENABLED_REF = 0x36dbdd0;
inline constexpr std::uintptr_t FOLLOW_AIM_REF = 0x36dbb00;
inline constexpr std::uintptr_t OWN_HEALTH_REF = 0x3d00aa8;
inline constexpr std::uintptr_t CLIENT_IMAGE_SIZE = 0x4226000;
inline constexpr std::uintptr_t TIER0_IMAGE_SIZE = 0x401000;
inline constexpr std::uintptr_t CVAR_DATA_SIZE = 0x5c;
inline constexpr std::uintptr_t CVAR_TYPE = 0x28;
inline constexpr std::uintptr_t CVAR_FLAGS = 0x30;
inline constexpr std::uintptr_t CVAR_VALUE = 0x58;
}
namespace FollowTarget {
inline constexpr CodeSpan TARGET_SPANS[] = {{0x1681c00, 121}, {0x86a6a0, 5}, {0x86a6b0, 92}, {0x83b4a0, 193}, {0x81b6b0, 17}, {0x81b6d0, 17}};
inline constexpr CodeSpan HEALTH_CONTEXT_SPANS[] = {{0x93a3e0, 33}, {0x1681be0, 23}, {0x57f910, 252}, {0x81b6b0, 17}, {0x81b6d0, 17}, {0x86a740, 137}, {0x1ba25b0, 297}, {0x1ba2c00, 65}, {0x81a0a0, 55}, {0x4a9210, 5}, {0x70f3e0, 3}, {0x1624ee5, 3}, {0x532f70, 3}, {0x58d976, 3}, {0x853910, 380}};
inline constexpr std::uintptr_t CONTROLLER_VTABLE = 0x27213e8;
inline constexpr std::uintptr_t OBSERVER_PAWN_VTABLE = 0x269e450;
inline constexpr std::uintptr_t PLAYER_PAWN_VTABLE = 0x26aaf38;
inline constexpr std::uintptr_t FAMILIAR_CLONE_PAWN_VTABLE = 0x288d1c8;
inline constexpr std::uintptr_t SERVICES_VTABLES[] = {0x2721e30, 0x2adb0d8};
inline constexpr std::uintptr_t CONTROLLER_FINAL_VTABLE = 0x27213b8;
inline constexpr std::uintptr_t OBSERVER_SERVICES_OFFSET = 0xe98;
inline constexpr std::uintptr_t ENTITY_LIST = 0x34c8038;
inline constexpr std::uintptr_t CONTROLLER = 0x3c9d510;
inline constexpr std::uintptr_t OBSERVER_PREDICATE = 0x532f70;
inline constexpr std::uintptr_t GET_OBSERVER_MODE = 0x86a6a0;
inline constexpr std::uintptr_t GET_OBSERVER_TARGET = 0x86a6b0;
inline constexpr std::uintptr_t PLAYER_PREDICATE = 0x165db30;
inline constexpr std::uintptr_t PLAYER_DATA_PREDICATE = 0x58db10;
inline constexpr std::uintptr_t CONTROLLER_PREDICATE = 0x70f3e0;
inline constexpr std::uintptr_t IDENTITY_STRIDE = 0x70;
inline constexpr std::uintptr_t IDENTITY_HANDLE = 0x10;
inline constexpr std::uintptr_t ENTITY_IDENTITY = 0x10;
inline constexpr std::uintptr_t CONTROLLER_PAWN = 0x6bc;
inline constexpr std::uintptr_t NETWORK_STATE = 0x3ef;
inline constexpr std::uintptr_t OBSERVER_PREDICATE_SLOT = 0x500;
inline constexpr std::uintptr_t OBSERVER_MODE_SLOT = 0xf0;
inline constexpr std::uintptr_t OBSERVER_TARGET_SLOT = 0x100;
inline constexpr std::uintptr_t OBSERVER_MODE = 0x48;
inline constexpr std::uintptr_t OBSERVER_TARGET = 0x4c;
inline constexpr std::uintptr_t PLAYER_PREDICATE_SLOT = 0x4e0;
inline constexpr std::uintptr_t PLAYER_DATA_PREDICATE_SLOT = 0xad8;
inline constexpr std::uintptr_t PAWN_CONTROLLER = 0x51c;
inline constexpr std::uintptr_t CONTROLLER_PREDICATE_SLOT = 0x4e8;
inline constexpr std::uintptr_t CONTROLLER_FINAL_DATA = 0x908;
}
namespace AttachRuntime {
inline constexpr char CLIENT_SHA256[] = "e2bafed8ebdfd239d506b4f59b24a09719f945c6a63f69766171349b886603d4";
inline constexpr std::uintptr_t CLIENT_IMAGE_SIZE = 0x4226000;
inline constexpr std::uintptr_t INITIALIZER = 0x209c590;
inline constexpr std::uintptr_t ENTITY_VTABLE = 0x2ac9b40;
inline constexpr std::uintptr_t ENTITY_GLOBAL = 0x3e1ed10;
inline constexpr unsigned char INITIALIZER_BYTES[] = {0xf, 0xb6, 0x44, 0x24, 0x28, 0x88, 0x44, 0x24, 0x28, 0x48, 0x89, 0xd, 0x70, 0x27, 0xd8, 0x1, 0xe9, 0x9b, 0xbf, 0xff, 0xff};
}
enum class AttachFieldIndex : unsigned { scene_node, owner, player_origin, player_angles, eye_offset, eye_angles, scene_child, scene_sibling };
inline constexpr std::size_t kViewOffsetComponents[] = {16, 24, 32};
} } // namespace dolly::reviewed
