"""Generated by tools/generate_compatibility.py; edit reviewed profiles, not this file."""

class Preload:
    CLIENT_SHA256 = 'e2bafed8ebdfd239d506b4f59b24a09719f945c6a63f69766171349b886603d4'
    RESOURCE_SHA256 = 'fba2c4733b0b3913ddf46cd26158f29b2ff87dfb06f9ab1b63da3361f0528800'
    MANAGER = 52537904
    MANAGER_VTABLE = 40637504
    RESOURCE_GLOBAL = 65676144
    RESOURCE_VTABLE = 441432
    RESOURCE_QUERY = 116832
    INTRO_GLOBAL = 63966520
    INTRO_VTABLE = 45525592
    CLIENT_CODE_SPANS = ((6245792, 8), (6283328, 126), (30740672, 266), (6184910, 51), (6296720, 10), (6137616, 75), (28412229, 101), (28528912, 230), (28684446, 465), (28588320, 66), (28445616, 554))
    MANAGER_SIZE = 64
    COMPLETED = 36
    RESOURCE = 48
    JOB = 56
    LIFECYCLE_BEGIN = 60
    LIFECYCLE_END = 62
    RESOURCE_QUERY_SLOT = 192
    RESOURCE_DONE = 68
    INTRO_SIZE = 132
    INTRO_PHASE = 128


class ReplayCamera:
    CLIENT_SHA256 = 'e2bafed8ebdfd239d506b4f59b24a09719f945c6a63f69766171349b886603d4'
    MANAGER = 57516912
    MANAGER_VTABLE = 40610688
    GAMEPLAY_CAMERA_VTABLE = 40641992
    RULES_GLOBAL = 63848800
    RULES_VTABLE = 40856792
    CODE_SPANS = ((6123808, 685), (6004048, 181), (25643568, 261), (25729648, 5), (25746320, 6), (28781984, 1642), (26315760, 88), (28453008, 17), (28659049, 112), (28755408, 91), (28781136, 118))
    RULES_STATE = 116
    MANAGER_SIZE = 72
    CURRENT_CAMERA = 40
    BLENDING = 56
    BLEND_WEIGHT = 68
    HUD_ROOT = 63963480
    HUD_ROOT_VTABLE = 45509760
    HUD_TAKEOVER_COUNT = 644


class FollowCapabilities:
    TIER0_SHA256 = '6793cc7306ff40283ba038a784fe96f99f6d38f93c825571ee93ab6b9d9d5332'
    CLIENT_SPANS = ((585664, 3430), (591632, 166), (2322416, 115), (38001216, 129), (2443552, 10), (6345174, 11))
    TIER0_SPANS = ((2161984, 633),)
    REFS = {'pivot_x_offset': 57523680, 'pivot_y_offset': 57523696, 'pivot_z_offset': 57523712, 'pivot_x_offset_crouching': 57523728, 'pivot_y_offset_crouching': 57523744, 'pivot_z_offset_crouching': 57523760, 'x_offset': 57523776, 'y_offset': 57523792, 'z_offset': 57523808, 'x_worst_case_offset': 57523824, 'y_worst_case_offset': 57523840, 'z_worst_case_offset': 57523856, 'ads_x_offset': 57523872, 'ads_y_offset': 57523888, 'ads_z_offset': 57523904, 'fov': 57523920, 'ads_fov': 57523936}
    OWN_HEALTH_SPANS = ((1818928, 174), (28702112, 803), (28579456, 47))
    ENABLED_REF = 57523664
    FOLLOW_AIM_REF = 57522944
    OWN_HEALTH_REF = 63965864
    CLIENT_IMAGE_SIZE = 69361664
    TIER0_IMAGE_SIZE = 4198400
    CVAR_DATA_SIZE = 92
    CVAR_TYPE = 40
    CVAR_FLAGS = 48
    CVAR_VALUE = 88


class FollowTarget:
    TARGET_SPANS = ((23600128, 121), (8824480, 5), (8824496, 92), (8631456, 193), (8500912, 17), (8500944, 17))
    HEALTH_CONTEXT_SPANS = ((9675744, 33), (23600096, 23), (5765392, 252), (8500912, 17), (8500944, 17), (8824640, 137), (28976560, 297), (28978176, 65), (8495264, 55), (4887056, 5), (7402464, 3), (23219941, 3), (5451632, 3), (5822838, 3), (8730896, 380))
    CONTROLLER_VTABLE = 41030632
    OBSERVER_PAWN_VTABLE = 40494160
    PLAYER_PAWN_VTABLE = 40546104
    FAMILIAR_CLONE_PAWN_VTABLE = 42521032
    SERVICES_VTABLES = (41033264, 44937432)
    CONTROLLER_FINAL_VTABLE = 41030584
    OBSERVER_SERVICES_OFFSET = 3736
    ENTITY_LIST = 55345208
    CONTROLLER = 63558928
    OBSERVER_PREDICATE = 5451632
    GET_OBSERVER_MODE = 8824480
    GET_OBSERVER_TARGET = 8824496
    PLAYER_PREDICATE = 23452464
    PLAYER_DATA_PREDICATE = 5823248
    CONTROLLER_PREDICATE = 7402464
    IDENTITY_STRIDE = 112
    IDENTITY_HANDLE = 16
    ENTITY_IDENTITY = 16
    CONTROLLER_PAWN = 1724
    NETWORK_STATE = 1007
    OBSERVER_PREDICATE_SLOT = 1280
    OBSERVER_MODE_SLOT = 240
    OBSERVER_TARGET_SLOT = 256
    OBSERVER_MODE = 72
    OBSERVER_TARGET = 76
    PLAYER_PREDICATE_SLOT = 1248
    PLAYER_DATA_PREDICATE_SLOT = 2776
    PAWN_CONTROLLER = 1308
    CONTROLLER_PREDICATE_SLOT = 1256
    CONTROLLER_FINAL_DATA = 2312


class AttachRuntime:
    CLIENT_SHA256 = 'e2bafed8ebdfd239d506b4f59b24a09719f945c6a63f69766171349b886603d4'
    CLIENT_IMAGE_SIZE = 69361664
    INITIALIZER = 34194832
    ENTITY_VTABLE = 44866368
    ENTITY_GLOBAL = 65137936
    INITIALIZER_BYTES = b"\x0f\xb6D$(\x88D$(H\x89\rp'\xd8\x01\xe9\x9b\xbf\xff\xff"


ATTACH_FIELD_SPECS = (('player_origin', 'CGameSceneNode', 'm_vecAbsOrigin', 'VectorWS', True), ('player_angles', 'CGameSceneNode', 'm_angAbsRotation', 'QAngle', True), ('eye_offset', 'C_BaseModelEntity', 'm_vecViewOffset', 'CNetworkViewOffsetVector', True), ('eye_angles', 'C_CitadelPlayerPawn', 'm_angEyeAngles', 'QAngle', True), ('scene_child', 'CGameSceneNode', 'm_pChild', 'CGameSceneNode*', True), ('scene_sibling', 'CGameSceneNode', 'm_pNextSibling', 'CGameSceneNode*', True), ('world_transform', 'CGameSceneNode', 'm_nodeToWorld', 'CTransformWS', False), ('attach_bone', 'CGameSceneNode', 'm_nParentAttachmentOrBone', 'int16', False), ('owner_entity', 'C_BaseEntity', 'm_hOwnerEntity', 'CHandle', False), ('pawn_controller', 'C_BasePlayerPawn', 'm_hController', 'CHandle', False))
ATTACH_WIRE_FIELDS = ('scene_node', 'owner', 'player_origin', 'player_angles', 'eye_offset', 'eye_angles', 'scene_child', 'scene_sibling')
VIEW_OFFSET_VALUE_OFFSETS = (16, 24, 32)
