"""Deadlock module compatibility scanning for Native camera mode.

This module is the single runtime source of truth for which installed game
modules a portable Dolly release can drive. It reads the bundled
``native/profiles/manifest.json`` (generated by ``tools/generate_profile.py``)
and hashes the installed ``client.dll``, ``engine2.dll`` and ``tier0.dll`` on
every launch. It never imports ``pefile``: the portable EXE runs without pip
dependencies, so the PE timestamp is read with ``struct`` directly.

A build is accepted only when every installed module hash is listed in the
manifest. Unrecognized builds are reported with the observed hash and the
reviewed date; they are never silently approved, because the native camera
depends on struct offsets and vtables that a signature alone cannot prove.
"""
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import struct
from typing import Any, Callable, Iterable
import uuid

from .runtime import resource_root

MANIFEST_FORMAT = 1
MODULE_RELATIVES: tuple[str, ...] = (
    "citadel/bin/win64/client.dll",
    "bin/win64/engine2.dll",
    "bin/win64/tier0.dll",
)
SUPPORTED = "supported"
UNSUPPORTED = "unsupported"
INCOMPLETE = "incomplete"


class CompatibilityError(RuntimeError):
    """The bundled compatibility manifest is missing or malformed."""


def manifest_path(source_root: Path | None = None) -> Path:
    root = resource_root(Path(__file__).resolve().parent.parent if source_root is None else source_root)
    return root / "native" / "profiles" / "manifest.json"


def hash_file(path: Path, chunk: int = 1024 * 1024) -> str:
    hasher = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(chunk), b""):
            hasher.update(block)
    return hasher.hexdigest()


def pe_timestamp(path: Path) -> int | None:
    """Return the PE ``TimeDateStamp`` without a PE-parsing dependency."""
    try:
        with path.open("rb") as stream:
            header = stream.read(0x40)
            if len(header) < 0x40 or header[:2] != b"MZ":
                return None
            offset = struct.unpack_from("<I", header, 0x3C)[0]
            if offset < 0x40 or offset > 0x100000:
                return None
            stream.seek(offset)
            coff = stream.read(12)
            if len(coff) < 12 or coff[:4] != b"PE\0\0":
                return None
            return struct.unpack_from("<I", coff, 8)[0]
    except OSError:
        return None


def _as_sha256(value: Any, field: str) -> str:
    if not isinstance(value, str) or len(value) != 64 or any(c not in "0123456789abcdef" for c in value):
        raise CompatibilityError(f"The compatibility manifest has an invalid {field}.")
    return value


def load_manifest(path: Path | None = None) -> dict[str, Any]:
    target = manifest_path() if path is None else Path(path)
    try:
        document = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise CompatibilityError("The native compatibility manifest is missing or unreadable; extract the complete Dolly release.") from exc
    if not isinstance(document, dict):
        raise CompatibilityError("The native compatibility manifest must be a JSON object.")
    if document.get("manifest_format") != MANIFEST_FORMAT or type(document.get("native_abi")) is not int:
        raise CompatibilityError("The native compatibility manifest has an unsupported format.")
    modules = document.get("modules")
    if not isinstance(modules, dict):
        raise CompatibilityError("The native compatibility manifest has no module list.")
    for relative in MODULE_RELATIVES:
        entry = modules.get(relative)
        if not isinstance(entry, dict):
            raise CompatibilityError(f"The compatibility manifest does not describe {relative}.")
        accepted = entry.get("accepted")
        if not isinstance(accepted, list) or not accepted:
            raise CompatibilityError(f"The compatibility manifest has no accepted hashes for {relative}.")
        for digest in accepted:
            _as_sha256(digest, f"hash for {relative}")
        if not isinstance(entry.get("reviewed_utc"), str):
            raise CompatibilityError(f"The compatibility manifest has no review date for {relative}.")
        if type(entry.get("latest_timestamp")) is not int:
            raise CompatibilityError(f"The compatibility manifest has no review timestamp for {relative}.")
    return document


def accepted_pins(manifest: dict[str, Any] | None = None) -> dict[str, tuple[str, ...]]:
    document = load_manifest() if manifest is None else manifest
    return {relative: tuple(document["modules"][relative]["accepted"]) for relative in MODULE_RELATIVES}


@dataclass(frozen=True)
class ModuleStatus:
    relative: str
    role: str
    installed: bool
    observed_sha256: str | None
    observed_timestamp: int | None
    accepted: tuple[str, ...]
    matched: bool
    reviewed_utc: str
    latest_timestamp: int

    @property
    def name(self) -> str:
        return Path(self.relative).name

    @property
    def newer_than_reviewed(self) -> bool:
        return bool(
            self.observed_timestamp is not None
            and self.observed_timestamp > self.latest_timestamp
        )


@dataclass(frozen=True)
class CompatibilityReport:
    state: str
    modules: tuple[ModuleStatus, ...]
    manifest: dict[str, Any] | None

    @property
    def unsupported_modules(self) -> tuple[ModuleStatus, ...]:
        return tuple(module for module in self.modules if module.installed and not module.matched)

    @property
    def missing_modules(self) -> tuple[ModuleStatus, ...]:
        return tuple(module for module in self.modules if not module.installed)

    @property
    def newest_update_module(self) -> ModuleStatus | None:
        newer = [module for module in self.unsupported_modules if module.newer_than_reviewed]
        if not newer:
            return None
        return max(newer, key=lambda module: module.observed_timestamp or 0)

    def describe(self) -> str:
        if self.state == SUPPORTED:
            return "The installed Deadlock modules match a reviewed Dolly compatibility profile."
        if self.state == INCOMPLETE:
            names = ", ".join(module.name for module in self.missing_modules)
            return f"Native camera could not find the installed game module(s): {names}."
        names = ", ".join(module.name for module in self.unsupported_modules)
        message = f"Native camera does not support this {names} build."
        updated = self.newest_update_module
        if updated is not None:
            message += (
                f" Deadlock appears to have been updated after Dolly's last review ({updated.reviewed_utc})."
                " Install a Dolly release that lists this build, or choose Console camera mode."
            )
        else:
            message += " Choose Console camera mode or use a native Dolly build for this Deadlock update."
        return message

    def details(self) -> str:
        lines = [f"Compatibility: {self.state}"]
        for module in self.modules:
            state = "ok" if module.matched else ("missing" if not module.installed else "unrecognized")
            observed = module.observed_sha256 or "n/a"
            lines.append(
                f"  {module.name}: {state} sha256={observed} reviewed={module.reviewed_utc}"
            )
        return "\n".join(lines)


def _normalize_pins(pins: dict[str, Iterable[str]]) -> dict[str, tuple[str, ...]]:
    return {
        relative: (value,) if isinstance(value, str) else tuple(value)
        for relative, value in pins.items()
    }


def _manifest_for(
    manifest: dict[str, Any] | None,
    pins: dict[str, Iterable[str]] | None,
) -> dict[str, Any]:
    """Select the manifest, optionally replacing accepted hashes with explicit pins."""
    if manifest is None:
        try:
            manifest = load_manifest()
        except CompatibilityError:
            manifest = None
    if pins is None:
        if manifest is None:
            raise CompatibilityError(
                "The native compatibility manifest is missing or unreadable; extract the complete Dolly release."
            )
        return manifest
    normalized = _normalize_pins(pins)
    modules: dict[str, Any] = {}
    for relative in MODULE_RELATIVES:
        accepted = normalized.get(relative)
        if accepted is None:
            raise CompatibilityError(f"No accepted hashes were provided for {relative}.")
        entry = dict(manifest.get("modules", {}).get(relative, {})) if manifest else {}
        entry.setdefault("role", Path(relative).stem)
        entry.setdefault("reviewed_utc", "unknown")
        entry.setdefault("latest_timestamp", 0)
        entry["accepted"] = list(accepted)
        modules[relative] = entry
    return {
        "manifest_format": MANIFEST_FORMAT,
        "native_abi": manifest.get("native_abi", 0) if manifest else 0,
        "modules": modules,
    }


def scan_game_modules(
    game_dir: Path,
    manifest: dict[str, Any] | None = None,
    hasher: Callable[[Path], str] | None = None,
    timestamp_reader: Callable[[Path], int | None] | None = None,
    pins: dict[str, Iterable[str]] | None = None,
) -> CompatibilityReport:
    """Classify the installed modules against the bundled manifest or explicit pins."""
    document = _manifest_for(manifest, pins)
    digest_of = hash_file if hasher is None else hasher
    timestamp_of = pe_timestamp if timestamp_reader is None else timestamp_reader
    game_dir = Path(game_dir)
    statuses: list[ModuleStatus] = []
    for relative in MODULE_RELATIVES:
        entry = document["modules"][relative]
        accepted = tuple(entry["accepted"])
        path = game_dir / relative
        if not path.is_file():
            statuses.append(ModuleStatus(
                relative=relative,
                role=entry.get("role", ""),
                installed=False,
                observed_sha256=None,
                observed_timestamp=None,
                accepted=accepted,
                matched=False,
                reviewed_utc=entry["reviewed_utc"],
                latest_timestamp=entry["latest_timestamp"],
            ))
            continue
        digest = digest_of(path)
        statuses.append(ModuleStatus(
            relative=relative,
            role=entry.get("role", ""),
            installed=True,
            observed_sha256=digest,
            observed_timestamp=timestamp_of(path),
            accepted=accepted,
            matched=digest in accepted,
            reviewed_utc=entry["reviewed_utc"],
            latest_timestamp=entry["latest_timestamp"],
        ))
    if any(not status.installed for status in statuses):
        state = INCOMPLETE
    elif all(status.matched for status in statuses):
        state = SUPPORTED
    else:
        state = UNSUPPORTED
    return CompatibilityReport(state=state, modules=tuple(statuses), manifest=document)


def report_identifier(report: CompatibilityReport) -> str:
    """A short stable token for logs and diagnostics."""
    return uuid.uuid5(uuid.NAMESPACE_URL, report.details()).hex[:12] if report else "unknown"
